AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Image Builder

Parameters:
  gitHubRepo:
    Type: String
    Default: https://github.com/seanghaeli/rcl-echo-cloud
  gitHubBranch:
    Default: master
    Type: String 
  Ec2KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  amazonLinuxAmi:
    Type: String 
    Description: Deep Learning AMI (Amazon Linux 2)

Resources:
  ImageBuilderLogBucket:
    Type: AWS::S3::Bucket

  ImageBuilderInstanceRole:
    Type: AWS::IAM::Role
    Metadata:
      Comment: Role to be used by instance during image build.
    Properties:
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Policies:
        - PolicyName: ECRGetAuthorizationTokenPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - ecr:GetAuthorizationToken
                Resource: "*"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: "2012-10-17"
      Path: /executionServiceEC2Role/

  InstanceRoleLoggingPolicy:
    Type: AWS::IAM::Policy
    Metadata:
      Comment: Allows the instance to save log files to an S3 bucket.
    Properties:
      PolicyName: ImageBuilderLogBucketPolicy
      Roles:
        - Ref: ImageBuilderInstanceRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - s3:PutObject
              - s3:GetObject
              - s3:HeadBucket
            Effect: Allow
            Resource:
            - Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: ImageBuilderLogBucket
                - /*

  ImageBuilderInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /executionServiceEC2Role/
      Roles:
        - Ref: ImageBuilderInstanceRole

  ContainerBuildComponent:
    Type: 'AWS::ImageBuilder::Component'
    Properties:
      Name: !Sub rcl-echo-cloud-Model-Builder-${AWS::StackName}
      Platform: 'Linux'
      Version: "1.0.0"
      Description:
        !Join
          - ''
          - - 'rcl-echo-cloud-Component-'
            - !Ref gitHubBranch
      ChangeDescription: 'change-description'
      # Require one of 'Data' or 'Uri' for Component template
      Data: 
        !Sub 
          - |-
            name: RclEchoCloudModel - InlineData
            description: RclEchoCloud Model Load
            schemaVersion: 1.0

            phases:                       
              - name: build
                steps:
                  - name: repoclone
                    action: ExecuteBash
                    inputs:
                      commands:
                        - |
                          aws configure set default.region ${awsRegion}
                          yum -y install git amazon-cloudwatch-agent jq                                    
                          yum -y install https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
                          alias cp="cp -f"
                          cd /root 
                          git clone ${gitHub} rcl-echo-cloud --branch ${gitBranch}
                          cp /root/rcl-echo-cloud/backend/sqs-ec2/amazon-cloudwatch-agent.json /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
                          cp /root/rcl-echo-cloud/backend/sqs-ec2/seelog.xml /etc/amazon/ssm/seelog.xml                          
                  - name: dockerlogin
                    action: ExecuteBash
                    inputs:
                      commands:          
                        - |
                          aws ecr get-login-password --region ${awsRegion} | docker login --username AWS --password-stdin 114170599997.dkr.ecr.${awsRegion}.amazonaws.com
                  - name: dockerpull
                    action: ExecuteBash
                    inputs:
                      commands:          
                        - docker pull 114170599997.dkr.ecr.${awsRegion}.amazonaws.com/view-classifier:latest
                        - docker tag  114170599997.dkr.ecr.${awsRegion}.amazonaws.com/view-classifier:latest view-classifier:latest
          - gitHub: !Ref gitHubRepo
            gitBranch: !Ref gitHubBranch
            awsRegion: !Sub '${AWS::Region}'

  ImageRecipe:
    Type: 'AWS::ImageBuilder::ImageRecipe'
    Properties:
      Name: !Sub rcl-echo-cloud-Model-Recipe-${AWS::StackName}
      Description:
        !Join
          - ''
          - - 'rcl-echo-cloud-Recipe-'
            - !Ref gitHubBranch
      Version: '1.0.0'
      ParentImage: !Ref amazonLinuxAmi
      Components:
        - ComponentArn: !Ref ContainerBuildComponent

  InfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: !Sub rcl-echo-cloud-Model-Infrastructure-${AWS::StackName}
      Description:
        !Join
          - ''
          - - 'rcl-echo-cloud-Infrastructure-'
            - !Ref gitHubBranch
      InstanceProfileName:
        Ref: ImageBuilderInstanceProfile
      # Set of one or more instance types to use when building the instance. Image Builder will select a type
      # based on availability.
      InstanceTypes:
        - 'g4dn.xlarge'
        - 'g4dn.2xlarge'
      KeyPair: 
        Ref: Ec2KeyName
      # Specify an S3 bucket and EC2 Image Builder will save logs to the bucket.
      Logging:
        S3Logs:
          S3BucketName:
            Ref: ImageBuilderLogBucket
          S3KeyPrefix: !Join [ "-", [ 'imagebuilder', !Ref "AWS::StackName" ] ]
      # If you would like to keep the instance running after a failed build, set TerminateInstanceOnFailure to false.
      TerminateInstanceOnFailure: false
      # If you do not have a default VPC or want to use a different VPC, you must specify the IDs of a subnet and one or more
      # security groups to be associated with the build instance.
      SubnetId: '{{resolve:ssm:/rcl-echo-cloud/subnet1:1}}' 
      SecurityGroupIds: 
        - '{{resolve:ssm:/rcl-echo-cloud/securitygroup:1}}'

  rclEchoCloudImage:
    Type: AWS::ImageBuilder::Image
    Properties:
      ImageRecipeArn:
        Ref: ImageRecipe
      InfrastructureConfigurationArn:
        Ref: InfrastructureConfiguration

  rclEchoCloudImagePipeline:
    Type: 'AWS::ImageBuilder::ImagePipeline'
    Properties:
      Name: !Sub rcl-echo-cloud-ImagePipeline-${AWS::StackName}
      Description:
        !Join
          - ''
          - - 'rcl-echo-cloud-ImagePipeline-'
            - !Ref gitHubBranch
      ImageRecipeArn: !Ref ImageRecipe
      InfrastructureConfigurationArn: !Ref InfrastructureConfiguration
      Status: 'DISABLED'

  # Create an SSM Parameter Store entry with our resulting ImageId.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html
  ImageParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Image Id for rclEchoCloud
      Name: !Sub /rcl-echo-cloud/${gitHubBranch}/imageid
      Type: String
      Value:
        Fn::GetAtt: [rclEchoCloudImage, ImageId]